# Generated by Django 4.0 on 2022-04-15 16:22

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, validators=[users.models.validate_email])),
                ('password', models.CharField(default='', max_length=20, validators=[users.models.validate_password])),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='admin', max_length=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
